version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:14.10.1 # the primary container, where your job's commands are run
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6b:0d:13:1f:91:e2:23:c1:fb:e8:e8:92:61:76:36:54"
      - checkout # 从仓库拉取代码
      - run:
         name: Install
         command: yarn install
      - run:
         name: Build
         command: yarn build
workflows:
  version: 2
  build-deploy:
   jobs:
    - build:
       filters:
         branches: 
          only: master